version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      web-deps:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /bot
    schedule:
      interval: weekly
    groups:
      bot-deps:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
